### ISSUE TITLE
What is the "hub"?

### ISSUE THREAD

**Issue by zoecarver** [stavinski/hubabuba#1]
I am wondering what I am supposed to put as the "hub" in the following:
```javascript
push.subscribe({
      id: "heroku",
      topic: "http://lorem-rss.herokuapp.com/feed?unit=second&interval=30",
      hub: "<what_here>"
    }
```
Thanks!

**Comment by stavinski** [comment]
The hub parameter is the hub provider to use see https://github.com/stavinski/hubabuba/blob/master/index.js#L143.

Most popular are either google at https://pubsubhubbub.appspot.com/ or superfeeder at https://pubsubhubbub.superfeedr.com.
